[package]
name = "U256"
version = "0.0.1"

[dependencies.MoveStdlib]
git = "https://github.com/borispovod/aptos-core.git"
rev = "b831fad66ea3b48d33a112e4fa8123c93d1db51d"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[addresses]
Sender = "0x1"


