[package]
name = "U256"
version = "0.3.4"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a58060f88d66b90a0548a506e22270b04a328db3"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }

[addresses]
u256 = "43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"