[package]
name = "U256"
version = "0.1.0"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[addresses]
Sender = "0x1"


